/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void billetter_dropList_click(GDropList source, GEvent event) { //_CODE_:billetter_dropList:237351:
  println("Billetter - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:billetter_dropList:237351:

public void reserver_button_click(GButton source, GEvent event) { //_CODE_:reserver_button:502515:
  println("Reserver - GButton >> GEvent." + event + " @ " + millis());
  logind_window.setVisible(true);
} //_CODE_:reserver_button:502515:

public void film_dropList_click(GDropList source, GEvent event) { //_CODE_:film_dropList:361568:
  println("film - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:film_dropList:361568:

public void afbestil_button_click(GButton source, GEvent event) { //_CODE_:afbestil_button:806271:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  afbestil_window.setVisible(true);
} //_CODE_:afbestil_button:806271:

synchronized public void win_draw2(PApplet appc, GWinData data) { //_CODE_:afbestil_window:889572:
  appc.background(20, 29, 38);
} //_CODE_:afbestil_window:889572:

public void afbestil_final_button_click(GButton source, GEvent event) { //_CODE_:afbetil_final_button:901157:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:afbetil_final_button:901157:

public void tlf_afbestil_textfield_change(GTextField source, GEvent event) { //_CODE_:tlf_afbestil_textfield:462433:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:tlf_afbestil_textfield:462433:

public void adg_afbestil_textfield_change(GTextField source, GEvent event) { //_CODE_:adg_afbestil_textfield:726572:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:adg_afbestil_textfield:726572:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:logind_window:857078:
  appc.background(20, 29, 38);
} //_CODE_:logind_window:857078:

public void tlf_logind_textfield_change(GTextField source, GEvent event) { //_CODE_:tlf_logind_textfield:973997:
  println("textfield3 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:tlf_logind_textfield:973997:

public void adg_logind_textfield_change(GTextField source, GEvent event) { //_CODE_:adg_logind_textfield:620999:
  println("textfield4 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:adg_logind_textfield:620999:

public void nybruger_button_click(GButton source, GEvent event) { //_CODE_:nybruger_button:361476:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:nybruger_button:361476:

public void logind_button_click(GButton source, GEvent event) { //_CODE_:logind_button:364978:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:logind_button:364978:

synchronized public void win_draw3(PApplet appc, GWinData data) { //_CODE_:nyprofil_window:682301:
  appc.background(20, 29, 38);
} //_CODE_:nyprofil_window:682301:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Biograf oversigt");
  billetter_dropList = new GDropList(this, 40, 90, 190, 300, 5, 30);
  billetter_dropList.setItems(loadStrings("list_237351"), 0);
  billetter_dropList.setLocalColorScheme(GCScheme.SCHEME_8);
  billetter_dropList.addEventHandler(this, "billetter_dropList_click");
  reserver_button = new GButton(this, 40, 620, 190, 50);
  reserver_button.setText("Reserver");
  reserver_button.setLocalColorScheme(GCScheme.SCHEME_8);
  reserver_button.addEventHandler(this, "reserver_button_click");
  film_dropList = new GDropList(this, 40, 10, 190, 200, 3, 30);
  film_dropList.setItems(loadStrings("list_361568"), 0);
  film_dropList.setLocalColorScheme(GCScheme.SCHEME_8);
  film_dropList.addEventHandler(this, "film_dropList_click");
  afbestil_button = new GButton(this, 1050, 620, 190, 50);
  afbestil_button.setText("Afbestil");
  afbestil_button.setLocalColorScheme(GCScheme.SCHEME_8);
  afbestil_button.addEventHandler(this, "afbestil_button_click");
  afbestil_label = new GLabel(this, 1030, 590, 230, 30);
  afbestil_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  afbestil_label.setText("Har du billetter der skal afbestilles?");
  afbestil_label.setLocalColorScheme(GCScheme.SCHEME_10);
  afbestil_label.setOpaque(false);
  afbestil_window = GWindow.getWindow(this, "Afbestil billetter", 0, 0, 500, 500, JAVA2D);
  afbestil_window.noLoop();
  afbestil_window.setActionOnClose(G4P.KEEP_OPEN);
  afbestil_window.addDrawHandler(this, "win_draw2");
  afbetil_final_button = new GButton(afbestil_window, 170, 270, 170, 50);
  afbetil_final_button.setText("Afbestil billetter");
  afbetil_final_button.addEventHandler(this, "afbestil_final_button_click");
  tlf_afbestil_textfield = new GTextField(afbestil_window, 160, 100, 190, 40, G4P.SCROLLBARS_NONE);
  tlf_afbestil_textfield.setPromptText("Telefon nr.");
  tlf_afbestil_textfield.setOpaque(true);
  tlf_afbestil_textfield.addEventHandler(this, "tlf_afbestil_textfield_change");
  adg_afbestil_textfield = new GTextField(afbestil_window, 160, 180, 190, 40, G4P.SCROLLBARS_NONE);
  adg_afbestil_textfield.setPromptText("Adgangskode");
  adg_afbestil_textfield.setOpaque(true);
  adg_afbestil_textfield.addEventHandler(this, "adg_afbestil_textfield_change");
  logind_window = GWindow.getWindow(this, "Window title", 0, 0, 500, 500, JAVA2D);
  logind_window.noLoop();
  logind_window.setActionOnClose(G4P.KEEP_OPEN);
  logind_window.addDrawHandler(this, "win_draw1");
  tlf_logind_textfield = new GTextField(logind_window, 140, 120, 210, 50, G4P.SCROLLBARS_NONE);
  tlf_logind_textfield.setPromptText("Telefon nr.");
  tlf_logind_textfield.setOpaque(true);
  tlf_logind_textfield.addEventHandler(this, "tlf_logind_textfield_change");
  adg_logind_textfield = new GTextField(logind_window, 140, 200, 210, 50, G4P.SCROLLBARS_NONE);
  adg_logind_textfield.setPromptText("Adgangskode");
  adg_logind_textfield.setOpaque(true);
  adg_logind_textfield.addEventHandler(this, "adg_logind_textfield_change");
  nybruger_button = new GButton(logind_window, 200, 390, 90, 30);
  nybruger_button.setText("Lav ny profil");
  nybruger_button.addEventHandler(this, "nybruger_button_click");
  logind_button = new GButton(logind_window, 140, 290, 210, 30);
  logind_button.setText("Log ind");
  logind_button.addEventHandler(this, "logind_button_click");
  nybruger_label = new GLabel(logind_window, 140, 360, 210, 30);
  nybruger_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  nybruger_label.setText("Har du ikke en bruger");
  nybruger_label.setOpaque(false);
  nyprofil_window = GWindow.getWindow(this, "Window title", 0, 0, 500, 500, JAVA2D);
  nyprofil_window.noLoop();
  nyprofil_window.setActionOnClose(G4P.KEEP_OPEN);
  nyprofil_window.addDrawHandler(this, "win_draw3");
  afbestil_window.loop();
  logind_window.loop();
  nyprofil_window.loop();
}

// Variable declarations 
// autogenerated do not edit
GDropList billetter_dropList; 
GButton reserver_button; 
GDropList film_dropList; 
GButton afbestil_button; 
GLabel afbestil_label; 
GWindow afbestil_window;
GButton afbetil_final_button; 
GTextField tlf_afbestil_textfield; 
GTextField adg_afbestil_textfield; 
GWindow logind_window;
GTextField tlf_logind_textfield; 
GTextField adg_logind_textfield; 
GButton nybruger_button; 
GButton logind_button; 
GLabel nybruger_label; 
GWindow nyprofil_window;
