/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void Antalbilletter(GDropList source, GEvent event) { //_CODE_:Billetter:237351:
  println("Billetter - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:Billetter:237351:

public void button1_click1(GButton source, GEvent event) { //_CODE_:Reserver:502515:
  println("Reserver - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Reserver:502515:

public void dropList2_click1(GDropList source, GEvent event) { //_CODE_:film:361568:
  println("film - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:film:361568:

public void button1_click3(GButton source, GEvent event) { //_CODE_:button1:806271:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:806271:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window_afbestil:889572:
  appc.background(230);
} //_CODE_:window_afbestil:889572:

public void button4_click2(GButton source, GEvent event) { //_CODE_:button4:901157:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button4:901157:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:462433:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:462433:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:textfield2:726572:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield2:726572:

synchronized public void win_draw2(PApplet appc, GWinData data) { //_CODE_:window1:857078:
  appc.background(230);
} //_CODE_:window1:857078:

public void textfield3_change1(GTextField source, GEvent event) { //_CODE_:textfield3:973997:
  println("textfield3 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield3:973997:

public void textfield4_change1(GTextField source, GEvent event) { //_CODE_:textfield4:620999:
  println("textfield4 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield4:620999:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:361476:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button2:361476:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:364978:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button3:364978:

synchronized public void win_draw7(PApplet appc, GWinData data) { //_CODE_:window2:682301:
  appc.background(230);
} //_CODE_:window2:682301:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Yeet");
  Billetter = new GDropList(this, 40, 90, 190, 300, 5, 10);
  Billetter.setItems(loadStrings("list_237351"), 0);
  Billetter.addEventHandler(this, "Antalbilletter");
  Reserver = new GButton(this, 40, 620, 190, 50);
  Reserver.setText("Reserver");
  Reserver.addEventHandler(this, "button1_click1");
  film = new GDropList(this, 40, 10, 190, 200, 3, 10);
  film.setItems(loadStrings("list_361568"), 0);
  film.addEventHandler(this, "dropList2_click1");
  button1 = new GButton(this, 1050, 620, 190, 50);
  button1.setText("Afbestil");
  button1.addEventHandler(this, "button1_click3");
  label1 = new GLabel(this, 1050, 590, 190, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("My label");
  label1.setOpaque(false);
  window_afbestil = GWindow.getWindow(this, "Afbestil billetter", 0, 0, 500, 500, JAVA2D);
  window_afbestil.noLoop();
  window_afbestil.setActionOnClose(G4P.CLOSE_WINDOW);
  window_afbestil.addDrawHandler(this, "win_draw1");
  button4 = new GButton(window_afbestil, 170, 270, 170, 50);
  button4.setText("Afbestil billetter");
  button4.addEventHandler(this, "button4_click2");
  textfield1 = new GTextField(window_afbestil, 160, 100, 190, 40, G4P.SCROLLBARS_NONE);
  textfield1.setPromptText("Telefon nr.");
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  textfield2 = new GTextField(window_afbestil, 160, 180, 190, 40, G4P.SCROLLBARS_NONE);
  textfield2.setPromptText("Adgangskode");
  textfield2.setOpaque(true);
  textfield2.addEventHandler(this, "textfield2_change1");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 500, 500, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.CLOSE_WINDOW);
  window1.addDrawHandler(this, "win_draw2");
  textfield3 = new GTextField(window1, 140, 120, 210, 50, G4P.SCROLLBARS_NONE);
  textfield3.setOpaque(true);
  textfield3.addEventHandler(this, "textfield3_change1");
  textfield4 = new GTextField(window1, 140, 200, 210, 50, G4P.SCROLLBARS_NONE);
  textfield4.setOpaque(true);
  textfield4.addEventHandler(this, "textfield4_change1");
  button2 = new GButton(window1, 200, 390, 90, 30);
  button2.setText("Face text");
  button2.addEventHandler(this, "button2_click1");
  button3 = new GButton(window1, 140, 290, 210, 30);
  button3.setText("Face text");
  button3.addEventHandler(this, "button3_click1");
  label2 = new GLabel(window1, 140, 360, 210, 30);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("My label");
  label2.setOpaque(false);
  window2 = GWindow.getWindow(this, "Window title", 0, 0, 500, 500, JAVA2D);
  window2.noLoop();
  window2.setActionOnClose(G4P.CLOSE_WINDOW);
  window2.addDrawHandler(this, "win_draw7");
  window_afbestil.loop();
  window1.loop();
  window2.loop();
}

// Variable declarations 
// autogenerated do not edit
GDropList Billetter; 
GButton Reserver; 
GDropList film; 
GButton button1; 
GLabel label1; 
GWindow window_afbestil;
GButton button4; 
GTextField textfield1; 
GTextField textfield2; 
GWindow window1;
GTextField textfield3; 
GTextField textfield4; 
GButton button2; 
GButton button3; 
GLabel label2; 
GWindow window2;
